
language: go

sudo: false

go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...
  
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
 
before_script:
  - go vet ./...

script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
